Ex1: Participant Exercise

    Define two variables called called age and income assign values 30 and 50000.0 respectively

    Write a print statement using f-string to print the output as following:

    "Age is: 30 Years and Income is: INR 50000.0"

    Write an if-else condition
        if age is more than 25 and less than 40 years and income is more than 30000.0 then set a variable named "approved" to True or set to False.


In [ ]:
age = 30
income = 50000.0
print(f"Age is: {age} Years and Income is: INR {income}")
approved = True if age>25 and age<40 and income>30000.0 else False
print(approved)

Age is: 30 Years and Income is: INR 50000.0
True


Age is: 30 Years and Income is: INR 50000.0

True

Ex2: Participant Exercise

    Write a function
        named getAgeGroup
        which takes a paramter age
        the default value of the age is 25
        it returns the age group as either "young" or "adult" or 'mid-age" or "old" based on age
            if age < 20, then return young
            if age >= 20, but < 35 then adult
            if age >= 35, but < 55 then mid-age
            if age > 55 then old
    Invoke the function with different ages and tes

In [ ]:
def getAgeGroup(age=25):
  if age <20:
    return "young"
  elif age >=20 and age <35:
    return "adult"
  elif age >=35 and age <55:
    return "mid-age"
  else:
    return "old"

print(getAgeGroup())
print(getAgeGroup(10))
print(getAgeGroup(25))
print(getAgeGroup(40))
print(getAgeGroup(60))

adult
young
adult
mid-age
old


Ex3: Participant Exercise

    Creata a list with the following 10 student names
        Krishnaa J., Jyoti Adhya, C. Haradas, Korravai Parikh, Saurandhri Vaknis, Sambridhi Holkar, Sita Padhy, Ambika Sanyal, Nehal Vadekar, Sarama Upalekar

    Create two lists named "math_scores" and "science_scores"

    Populate the above two variables with randomly generated numbers between 20 and 90

    Both the scores should have exactly 10 items only. Assume that the names and scores are mapped in the same sequence.

    Write a function which takes math and science score of each individual returns the total score and grade
        Grade is Pass if both the scores are greater than equal to 50
        Grade is Fail if any one of the scores is less than 50
        The function should return a tuple with total score and grade e.g. (110, "Pass")

    Iterate through the student names and invoke the above function

    Store all information in a dictionary with names as keys and results (tuple with total score and grade) as values.

    Print the dictionary




In [14]:
from random import randint

def checkScores(name, math, science):
  total = math + science
  if math>=50 and science>=50:
    return(total, "Pass")
  else: return(total, "Fail")

student_names = ["Krishnaa J.", "Jyoti Adhya", "C. Haradas", "Korravai Parikh", "Saurandhri Vaknis", "Sambridhi Holkar", "Sita Padhy", "Ambika Sanyal", "Nehal Vadekar, Sarama Upalekar"]
math_scores=[]
science_scores=[]
ans={}

for i in range(0, len(student_names)):
  math_scores.append(randint(20,90))
  science_scores.append(randint(20,90))

for i in range(0, len(student_names)):
  ans[student_names[i]]=checkScores(student_names[i],math_scores[i],science_scores[i])

print(ans)


{'Krishnaa J.': (119, 'Fail'), 'Jyoti Adhya': (91, 'Fail'), 'C. Haradas': (112, 'Fail'), 'Korravai Parikh': (77, 'Fail'), 'Saurandhri Vaknis': (89, 'Fail'), 'Sambridhi Holkar': (98, 'Fail'), 'Sita Padhy': (122, 'Pass'), 'Ambika Sanyal': (66, 'Fail'), 'Nehal Vadekar, Sarama Upalekar': (78, 'Fail')}


{'Krishnaa J.': (119, 'Fail'), 'Jyoti Adhya': (91, 'Fail'), 'C. Haradas': (112, 'Fail'), 'Korravai Parikh': (77, 'Fail'), 'Saurandhri Vaknis': (89, 'Fail'), 'Sambridhi Holkar': (98, 'Fail'), 'Sita Padhy': (122, 'Pass'), 'Ambika Sanyal': (66, 'Fail'), 'Nehal Vadekar, Sarama Upalekar': (78, 'Fail')}



Ex4: Participant Exercise

    The variable daily_prices contains information about a stock open and close prices for 10 days
    Calculate the daily gains and create a dictionary which stores the date and daily gains as shown below

[{'Date': '17-05-2016', 'Gain': -0.32},
 {'Date': '16-05-2016', 'Gain': 0.33},
 {'Date': '13-05-2016', 'Gain': -0.02},
 {'Date': '12-05-2016', 'Gain': 0.1},
 {'Date': '11-05-2016', 'Gain': -0.33},
 {'Date': '10-05-2016', 'Gain': 1.05},
 {'Date': '09-05-2016', 'Gain': 0.77},
 {'Date': '06-05-2016', 'Gain': -0.89},
 {'Date': '05-05-2016', 'Gain': 0.12},
 {'Date': '04-05-2016', 'Gain': -0.12}]

    The gain should be calculated as (Close - Open) *100 / Open.
    The gain value should be rounded to 2 decimal places
    Accomplish the above task using both the approaches: List comprehension and map() function



In [17]:


daily_prices = [ {'Date': '17-05-2016', 'Open': 1218.0, 'Close': 1214.05005},
                 {'Date': '16-05-2016', 'Open': 1210.0, 'Close': 1213.94995},
                 {'Date': '13-05-2016', 'Open': 1207.0, 'Close': 1206.69995},
                 {'Date': '12-05-2016', 'Open': 1208.94995, 'Close': 1210.19995},
                 {'Date': '11-05-2016', 'Open': 1205.0, 'Close': 1201.05005},
                 {'Date': '10-05-2016', 'Open': 1200.0, 'Close': 1212.55005},
                 {'Date': '09-05-2016', 'Open': 1190.0, 'Close': 1199.1500199999998},
                 {'Date': '06-05-2016', 'Open': 1192.0, 'Close': 1181.44995},
                 {'Date': '05-05-2016', 'Open': 1191.0, 'Close': 1192.44995},
                 {'Date': '04-05-2016', 'Open': 1191.0, 'Close': 1189.55005}]

def calcGain(d):
  ans={}
  gain=round((d["Close"]-d["Open"])*100/d["Open"],2)
  ans["Date"]=d["Date"]
  ans["Gain"]=gain
  return ans

ans_list=[calcGain(daily_price) for daily_price in daily_prices]
print(ans_list)

[{'Date': '17-05-2016', 'Gain': -0.32}, {'Date': '16-05-2016', 'Gain': 0.33}, {'Date': '13-05-2016', 'Gain': -0.02}, {'Date': '12-05-2016', 'Gain': 0.1}, {'Date': '11-05-2016', 'Gain': -0.33}, {'Date': '10-05-2016', 'Gain': 1.05}, {'Date': '09-05-2016', 'Gain': 0.77}, {'Date': '06-05-2016', 'Gain': -0.89}, {'Date': '05-05-2016', 'Gain': 0.12}, {'Date': '04-05-2016', 'Gain': -0.12}]


In [21]:
daily_prices = [ {'Date': '17-05-2016', 'Open': 1218.0, 'Close': 1214.05005},
                 {'Date': '16-05-2016', 'Open': 1210.0, 'Close': 1213.94995},
                 {'Date': '13-05-2016', 'Open': 1207.0, 'Close': 1206.69995},
                 {'Date': '12-05-2016', 'Open': 1208.94995, 'Close': 1210.19995},
                 {'Date': '11-05-2016', 'Open': 1205.0, 'Close': 1201.05005},
                 {'Date': '10-05-2016', 'Open': 1200.0, 'Close': 1212.55005},
                 {'Date': '09-05-2016', 'Open': 1190.0, 'Close': 1199.1500199999998},
                 {'Date': '06-05-2016', 'Open': 1192.0, 'Close': 1181.44995},
                 {'Date': '05-05-2016', 'Open': 1191.0, 'Close': 1192.44995},
                 {'Date': '04-05-2016', 'Open': 1191.0, 'Close': 1189.55005}]

def calcGain(d):
  ans={}
  gain=round((d["Close"]-d["Open"])*100/d["Open"],2)
  ans["Date"]=d["Date"]
  ans["Gain"]=gain
  return ans

ans_list=list(map(calcGain, daily_prices))
print(ans_list)

[{'Date': '17-05-2016', 'Gain': -0.32}, {'Date': '16-05-2016', 'Gain': 0.33}, {'Date': '13-05-2016', 'Gain': -0.02}, {'Date': '12-05-2016', 'Gain': 0.1}, {'Date': '11-05-2016', 'Gain': -0.33}, {'Date': '10-05-2016', 'Gain': 1.05}, {'Date': '09-05-2016', 'Gain': 0.77}, {'Date': '06-05-2016', 'Gain': -0.89}, {'Date': '05-05-2016', 'Gain': 0.12}, {'Date': '04-05-2016', 'Gain': -0.12}]
